In [36]:
'''dahyun+darwin = dahwin'''
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [37]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

Logistic Regression

In [38]:
logistic = LogisticRegression()
logistic.fit(X_train,y_train)
logistic.score(X_test,y_test)

C:\Users\Pc\Desktop\machine_Learning\mldl\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9703703703703703

Support Vactor Machine

In [39]:
svm = SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9907407407407407

Random Forest

In [40]:
random = RandomForestClassifier()
random.fit(X_train,y_train)
random.score(X_test,y_test)

0.975925925925926

<h2 style='color:purple'>KFold cross validation</h2>

In [41]:
from sklearn.model_selection import KFold
kf = KFold()
kf

KFold(n_splits=5, random_state=None, shuffle=False)

In [42]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[2 3 4 5 6 7 8] [0 1]
[0 1 4 5 6 7 8] [2 3]
[0 1 2 3 6 7 8] [4 5]
[0 1 2 3 4 5 8] [6 7]
[0 1 2 3 4 5 6 7] [8]


In [43]:
def get_score(model,x_train,x_test,y_train,y_test):
    model.fit(x_train,y_train)
    return model.score(x_test,y_test)

In [44]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold()
scores_logistic = []
scores_svm = []
scores_random = []
for train_index,test_index in folds.split(digits.data,digits.target):
    x_train,x_test,y_train,y_test = digits.data[train_index],digits.data[test_index],\
                                    digits.target[train_index],digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'),x_train,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),x_train,x_test,y_train,y_test))#gamma='auto'
    scores_random.append(get_score(RandomForestClassifier(),x_train,x_test,y_train,y_test))#n_estimators=40

In [45]:
scores_logistic

[0.9222222222222223,
 0.8833333333333333,
 0.9526462395543176,
 0.958217270194986,
 0.8941504178272981]

In [46]:
scores_svm

[0.9611111111111111,
 0.9444444444444444,
 0.9832869080779945,
 0.9888579387186629,
 0.9387186629526463]

In [47]:
scores_random

[0.9388888888888889,
 0.9055555555555556,
 0.958217270194986,
 0.9610027855153204,
 0.9164345403899722]

In [48]:
from sklearn.model_selection import cross_val_score

Logistic regression model performance using cross_val_score

In [51]:
cross_val_score(LogisticRegression(),digits.data, digits.target,cv=3)

C:\Users\Pc\Desktop\machine_Learning\mldl\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
C:\Users\Pc\Desktop\machine_Learning\mldl\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.

array([0.92153589, 0.94156928, 0.91652755])

In [53]:
cross_val_score(SVC(),digits.data, digits.target,cv=3)

array([0.96494157, 0.97996661, 0.96494157])

In [54]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target,cv=3)

array([0.94490818, 0.94824708, 0.92320534])

<h2 style='color:purple'>Parameter tunning using k fold cross validation</h2>

In [59]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),digits.data, digits.target, cv=10)
np.average(scores1)

0.8775760397268776

In [61]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=20),digits.data, digits.target, cv=10)
np.average(scores2)

0.9348789571694598

In [62]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),digits.data, digits.target, cv=10)
np.average(scores3)

0.9504562383612661

In [63]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9549348230912477

In [66]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),digits.data, digits.target, cv=10)
np.average(scores4)

0.9465580384854129